### ISSUE TITLE
[Question]: How to generate development version of main.min.js to debug some errors  when updating Meshcat

### ISSUE THREAD

**Issue by wpumacay** [GiulioRomualdi/meshcat-cpp#17]
Hi @traversaro , @GiulioRomualdi . I'm trying to update the `Meshcat` version to the latest, which has also an updated Three-JS version. So far I was able to update and add the Capsule geometry, but the Mesh geometry is not being loaded. It seems it is an error on the JS side, so I was wondering if you could give me any pointers on how to generate the unminified version of the `main.min.js`. I tried fiddling with the build of meshcatr and got an unminified version, but it seems it's the wrong one as it doesn't load.

Thanks in advance for any help.

**Comment by traversaro** [comment]
Hello @wpumacay ! I am a bit confused, from what I understand updating meshcat would mean updating the `main.min.js` after getting it from https://github.com/meshcat-dev/meshcat, eventually following the instructions in https://github.com/meshcat-dev/meshcat?tab=readme-ov-file#developing-meshcat?tab=readme-ov-file#developing-meshcat to create a new `main.min.js` . Why you want to unminify `main.min.js` ?

**Comment by wpumacay** [comment]
Hi @traversaro . Oh, it's because I've already updated the main.min.js to add support for capsules. I added the support and everything works fine, except the mesh geometries. In the example, the dragonite doesn't load, and it returns an error on javascript related to an invalid length for a typed array. I wanted to debug this further by having the unminified version of the main.min.js so I could see where the error is actually happening and try to fix it. It seems it's an issue with the stl loader, but can't figure out exactly what is the error.

Sorry I posted it here, I think I should have posted it in the Meshcat repo, but if you have any hints of how to debug this issue I would really appreciate it.

**Comment by traversaro** [comment]
@wpumacay just out of curiosity, how did you solved the problem in the end?

**Comment by wpumacay** [comment]
@traversaro Oh sorry I havent' solved it yet. I thought this question should be asked in Meshcat repo instead, as it's a question related to the visualizer itself, not the bridge interface (even though the issue might be a misconfiguration on my end when I updated meshcat :sweat_smile:) . I posted a [question](https://github.com/meshcat-dev/meshcat/issues/184) just today in that repo, I'll let you know what they suggest :+1:

**Comment by wpumacay** [comment]
Hi @traversaro . You can generate the dev build `main.js` by modifying the [`webpack.config.js`](https://github.com/meshcat-dev/meshcat/blob/df31f9c357ba37121dc38d463ac94780204a3e37/webpack.config.js#L3). Just add the `filename` entry as follows:

```js
module.exports = [{
    entry: './src/index.js',
    output: {
        filename: "main.js",
        library: "MeshCat",
        libraryTarget: 'umd'
    },
    watch: true,
    mode: "development",
    devtool: "eval-cheap-source-map"
}, { ...
```
Also, update the [`rebuild.sh`](https://github.com/meshcat-dev/meshcat/blob/df31f9c357ba37121dc38d463ac94780204a3e37/rebuild/rebuild.sh#L40) by adding `main.js` to the list of options in the for loop.

```js
# Copy the relevant webpack outputs into `meshcat/dist/.
for name in main.js main.min.js main.min.js.THIRD_PARTY_LICENSES.json; do
  docker cp ${container}:/usr/src/app/dist/${name} ../dist/
done
```

This will generate the `main.js`. Just replace any ocurrance of `main.min.js` with this new file (create a backup just in case).

**Comment by traversaro** [comment]
Thanks!
